language: cpp
compiler: clang

matrix:
    include:
        - os: osx
          install:
		    - pip install gitpython
            - pip install conan
          script:
            - python3 build.py --build
#        - os: linux
#          sudo: required 
#          dist: trusty
#          install: 
#            - sudo pip install conan
#          script: 
#            - python3 build.py --build
