language: cpp

matrix:
    include:
        - os: osx
          compiler: clang
          install:
            - pip install conan
#        - os: linux
#          sudo: required 
#          dist: trusty
#          compiler: gcc
#          install: 
#            - sudo pip install conan
install:
- conan user
script: 
- python3 build.py --make
