language: cpp

matrix:
    include:
        - os: osx
          name: macOS
          install:
            - pip3 install gitpython
            - pip3 install conan
          script:
            - python3 build.py --build
        - os: osx
          name: iOS
          install:
            - pip3 install gitpython
            - pip3 install conan
          script:
            - python3 build.py --build --ios
        - os: linux
          name: Linux
          sudo: required 
          dist: xenial
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-8
          install: 
            - sudo apt update
            - sudo apt install python3-pip
            - sudo pip3 install conan
            - sudo pip3 install gitpython
          script: 
              - python3 build.py --build
