language: cpp

matrix:
    include:
#        - os: osx
#          install:
#            - pip3 install gitpython
#            - pip3 install conan
#          script:
#            - python3 build.py --build
        - os: linux
          sudo: required 
          dist: trusty
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-7
          install: 
            - sudo apt-get install binutils
            - sudo binutils-config -l
            - sudo binutils-config x86_64-pc-linux-gnu-2.29.1
            - sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            - sudo python3 get-pip.py
            - sudo pip install conan
            - sudo pip install gitpython
          script: 
              - python3 build.py --build
