language: cpp

matrix:
    include:
        - os: osx
          compiler: clang
        - os: linux
          sudo: required 
          dist: trusty
          compiler: gcc
install:
- pip install conan
- conan user
script: 
- python3 build.py --make
