language: cpp
compiler: clang

matrix:
    include:
        - os: osx
          install:
            - pip install conan
          script: 
            - python3 build.py --make
        - os: linux
          sudo: required 
          dist: trusty
          install: 
            - sudo pip install conan
          script: 
            - python3 build.py --make --clang
