language: cpp

matrix:
    include:

        - os: osx
          name: iOS simulator
          install:
            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          script:
            - python3 build.py --build --ios --no-conan --no-ios-exe

        - os: osx
          name: iOS device
          install:
            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          script:
            - python3 build.py --build --ios --device --no-freetype --no-assimp --no-bullet3 --no-ios-exe

        - os: osx
          name: macOS
          install:
            - brew update-reset
            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          script:
            - python3 build.py --build

        - os: linux
          name: Linux
          dist: focal
          install:
            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          script:
            - python3 build.py --build
