language: cpp
compiler: gcc

matrix:
    include:
#        - os: osx
#          install:
#            - pip3 install gitpython
#            - pip3 install conan
#          script:
#            - python3 build.py --build
        - os: linux
          sudo: required 
          dist: trusty
          install: 
            - sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            - sudo python3 get-pip.py
            - sudo pip install conan
            - sudo pip install gitpython
          script: 
            - python3 build.py --build
