language: cpp

matrix:
    include:
        
        - os: osx
          name: iOS simulator
          install:
            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          script:
            - python3 build.py --build --ios --no-conan
        
        - os: osx
          name: iOS device
          install:
            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          script:
            - python3 build.py --build --ios --device --no-conan
        
        - os: osx
          name: macOS
          install:
            - brew update-reset
            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          script:
            - python3 build.py --build
        
        - os: linux
          name: Linux
          sudo: required 
          dist: xenial
          addons:
            apt:
                sources:    
                    - ubuntu-toolchain-r-test   
                packages:
                    - g++-7
          install: 
            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          script: 
            - python3 build.py --build

        - os: linux
          name: Android
          sudo: required 
          dist: xenial
          components:
            - build-tools-26.0.2
            - android-26

            - extra-google-google_play_services
            - extra-google-m2repository
            - extra-android-m2repository
            - addon-google_apis-google-26

            - sys-img-armeabi-v7a-android-26
            - sys-img-armeabi-v7a-android-17
          before_install:
            - curl -L http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip -O
            - unzip -oq android-ndk-r16b-linux-x86_64.zip
            - rm android-ndk-r16b-linux-x86_64.zip
            - export ANDROID_NDK_HOME=`pwd`/android-ndk-r16b
          install: 
            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
          script: 
            - python3 build.py --prepare --android --no-conan
            - cd android/
            - ./gradlew assembleDebug
