language: cpp

matrix:
    include:

        - os: windows
          name: Windows MinGW
          before_install:
            - python --version
            - python3 --version
            - py --version
            - choco install python3
            - python --version
            - python3 --version
            - py --version
          install:
            - git clone https://github.com/vladasz/deploy
            - python3 deploy/deploy.py
          script:
            - python3 build.py --build
#
#        - os: osx
#          name: iOS simulator
#          install:
#            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
#          script:
#            - python3 build.py --build --ios --no-conan --no-ios-exe
#
#        - os: osx
#          name: iOS device
#          install:
#            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
#          script:
#            - python3 build.py --build --ios --device --no-conan --no-ios-exe
#
#        - os: osx
#          name: macOS
#          install:
#            - brew update-reset
#            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
#          script:
#            - python3 build.py --build
#
#        - os: linux
#          name: Linux
#          dist: bionic
#          addons:
#            apt:
#                sources:
#                    - ubuntu-toolchain-r-test
#                packages:
#                    - g++-7
#          install:
#            - git clone https://github.com/vladasz/deploy; python3 deploy/deploy.py
#          script:
#            - python3 build.py --build
