language: cpp

matrix:
    include:
#        - os: osx
#          install:
#            - pip3 install gitpython
#            - pip3 install conan
#          script:
#            - python3 build.py --build
        - os: linux
          sudo: required 
          dist: trusty
          compiler: clang
          addons:
             apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - llvm-toolchain-trusty-6.0
             packages: 
                - clang-6.0
                - libstdc++-7-dev
          install: 
            - sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            - sudo python3 get-pip.py
            - sudo pip install conan
            - sudo pip install gitpython
          script: 
              - python3 build.py --build --clang
