language: cpp

matrix:
    include:
#        - os: osx
#          install:
#            - pip3 install gitpython
#            - pip3 install conan
#          script:
#            - python3 build.py --build
        - os: linux
          sudo: required 
          dist: trusty
          packages:
            - g++-7
            - clang-5.0
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
          install: 
            - sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            - sudo python3 get-pip.py
            - sudo pip install conan
            - sudo pip install gitpython
          script: 
              - gcc-7 -v
              - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
              - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
              - sudo ln -s /usr/bin/gcc-7 gcc
              - sudo ln -s /usr/bin/g++-7 g++
              - export CC=/usr/bin/gcc-7
              - export CXX=/usr/bin/g++-7
              - gcc -v && g++ -v
              - python3 build.py --build --clang

before_install:
    - eval "${MATRIX_EVAL}"
