version: "{build}"

os:
  - Visual Studio 2017

clone_script:
  - cmd: git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%  

install:
  - py --version
  - pip install conan
  - git clone --recursive https://github.com/vladasz/utils			
  - py Build.py --ide

build:
  project: build/TestEngine.sln
  parallel: true                        
  verbosity: normal
