version: "{build}"

os:
  - Visual Studio 2017

install:
  - git clone https://github.com/vladasz/deploy; py deploy/deploy.py
  - py build.py --ide
  
configuration:
  - Release

build:
  project: build/test_engine.sln
  parallel: true                        
  verbosity: normal
