version: "{build}"

os:
  - Visual Studio 2017

install:
  - git submodule update --init --recursive  
  - pip3 install conan
  - pip3 install gitpython
  - py build.py --ide
  
configuration:
  - Release

build:
  project: build/test_engine.sln
  parallel: true                        
  verbosity: normal
