version: "{build}"

os:
  - Visual Studio 2019

install:
  - py --version
  - git clone https://github.com/vladasz/deploy
  - py deploy/deploy.py
  - py build.py --prepare --ide --debug --vs19
  
configuration:
  - Debug

build:
  project: build/test_engine.sln
  parallel: true                        
  verbosity: normal
